app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
    path('', views.IndexMain.as_view())
]

blog/urls.py
from django.urls import path
from . import views
from blog.views import Index

app_name = 'blog'

# 기본 구조
# urlpatterns = [
#     # path(패턴, 매핑)
# ]

urlpatterns = [
    # path("", views.index), # FBV way
    # 글 목록 조회
    path("", views.Index.as_view(), name='list'),  # /blog/

    # 글 상세 조회
    path("detail/<int:pk>", views.DetailView.as_view(), name='detail'),
    # 글 작성
    path("write/", views.Write.as_view(), name='write'),
    # 글 수정
    path("detail/<int:pk>/edit/", views.Update.as_view(), name='edit'),
    # 글 삭제
    path("detail/<int:pk>/delete/", views.Delete.as_view(), name='delete'),
    # 코멘트 작성
    path("detail/<int:pk>/comment/write/",
         views.CommentWrite.as_view(), name='cm-write'),
    # 코멘트 삭제
    path("detail/comment/<int:pk>/delete/",
         views.CommentDelete.as_view(), name='cm-delete'),
    # 태그 생성
    path("detail/<int:pk>/hashtag/write/",
         views.HashTagWrite.as_view(), name="tag-write"),
    # 태그 삭제
    path("detail/<int:pk>/hashtag/delete/",
         views.HashTagDelete.as_view(), name='tag-delete'),
]

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Post(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content


class HashTag(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name

blog/forms.py
# blog/forms.py
from django import forms
from .models import Post, Comment, HashTag

# Form

# Model Form 
class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ['title', 'content']


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['content']


class HashTagForm(forms.ModelForm):

    class Meta:
        model = HashTag
        fields = ['name']

blog/views.py
from typing import Any, Dict
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import View
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Post, Comment, HashTag
from .forms import PostForm, CommentForm, HashTagForm
from django.urls import reverse_lazy, reverse

# Create your views here.
# def index(request):
#     if request.method == 'GET':
#         return HttpResponse('Index page GET')
#     elif request.method == 'POST':
#         return HttpResponse('Index page POST')
#     else:
#         return HttpResponse('Invalid method')

# 포스트


class Index(View):
    def get(self, request):
        # return HttpResponse('index page Get class')

        # 데이터베이스에 접근해서 값을 가져와야 합니다.
        # 게시판에 글들을 보여줘야하기 떄문에 데이터베이스에서 "값 조회" all()
        # MyModel.objects.all()
        post_objs = Post.objects.all()
        # context = 데이터베이스에서 가져온 값
        context = {
            "posts": post_objs,
            "title": "Blog"
        }
        return render(request, 'blog/post_list.html', context)


# def write(request):
#     if request.method == 'POST':
#         # form 확인
#         form = PostForm(request.POST)
#         if form.is_valid():
#             post = form.save()
#             return redirect('blog:list')

#     form = PostForm()
#     return render(request, 'blog/write.html', {'form': form})


# Django 자체의 클래스 뷰 기능도 강력, 편리
# model, template_name, context_object_name,
# paginate_by, form_class, form_valid(), get_queryset()
# django.views.generitc - > ListView
# class List(ListView):
#     model = Post  # 모델
#     template_name = 'blog/post_list.html'  # 템플릿
#     context_object_name = 'posts'  # 변수 값의 이름


# class Write(CreateView):
#     model = Post  # 모델
#     form_class = PostForm  # 폼
#     success_url = reverse_lazy('blog:list')  # 성공시 보내줄 url


class Write(LoginRequiredMixin, View):

    def get(self, request):
        form = PostForm()
        context = {
            'form': form
        }
        return render(request, 'blog/post_form.html', context)

    def post(self, request):
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.writer = request.user
            post.save()
            return redirect('blog:list')
        form.add_error(None, '폼이 유효하지 않습니다.')
        context = {
            'form': form,
            "title": "Blog"
        }
        return render(request, 'blog/post_form.html')


# class Detail(DetailView):
#     model = Post
#     template_name = 'blog/post_detail.html'
#     context_object_name = 'post'


# class Update(UpdateView):
#     model = Post
#     template_name = 'blog/post_edit.html'
#     fields = ['title', 'content']
#     # success_url = reverse_lazy('blog:list')
#     # initial 기능 사용 -> form에 값을 미리 넣어주기 위해서

#     def get_initial(self):
#         initial = super().get_initial()  # UpdateView(generic view)에서 제공하는 initial(딕셔너리)
#         post = self.get_object()  # pk 기반으로 객체를 가져옴
#         initial['title'] = post.title
#         initial['content'] = post.content
#         return initial

#     def get_success_url(self):
#         post = self.get_object()  # pk 기반으로 현재 객체 가져오기
#         return reverse('blog:detail', kwargs={'pk': post.pk})

class Update(View):
    def get(self, request, pk):  # post_id
        post = Post.objects.get(pk=pk)
        form = PostForm(initial={'title': post.title, 'content': post.content})
        context = {
            'form': form,
            'post': post,
            "title": "Blog"
        }
        return render(request, 'blog/post_edit.html', context)

    def post(self, request, pk):
        post = Post.objects.get(pk=pk)
        form = PostForm(request.POST)
        if form.is_valid():
            post.title = form.cleaned_data['title']
            post.content = form.cleaned_data['content']
            post.save()
            return redirect('blog:detail', pk=pk)

        form.add_error('폼이 유효하지 않습니다.')
        hashrag_form = HashTagForm()
        context = {
            'form': form,
            'post': post,
            "title": "Blog"
        }
        return render(request, 'blog/post_detail_error.html', context)

# class Delete(DeleteView):
#     model = Post
#     success_url = reverse_lazy('blog:list')


class Delete(View):
    def post(self, request, pk):
        post = Post.objects.get(pk=pk)
        post.delete()
        return redirect('blog:list')


class DetailView(View):
    def get(self, request, pk):
        # 글 가져옴
        post = Post.objects.get(pk=pk)

        comments = Comment.objects.filter(post=post)
        hashtags = HashTag.objects.filter(post=post)

        # 태그 form
        hashtag_form = HashTagForm()

        # 댓글 form
        comment_form = CommentForm()

        context = {
            "title": "Blog",
            'post': post,
            'comments': comments,
            'hashtags': hashtags,
            'comment_form': comment_form,
            'hasgtag_form': hashtag_form,
            "title": "Blog"
        }

        return render(request, 'blog/post_detail.html', context)
        # 댓글


# Comment
class CommentWrite(View):
    def post(self, request, pk):
        form = CommentForm(request.POST)
        post = Post.objects.get(pk=pk)
        if form.is_valid():
            # 사용자에게 댓글 내용을 받아옴
            content = form.cleaned_data['content']
            # 해당 아이디에 해당하는 글 불러옴
            post = Post.objects.get(pk=pk)
            # 유저 정보 가져오기
            writer = request.user
            # 댓글 객체 생성
            comment = Comment.objects.create(
                post=post, content=content, writer=writer)
            return redirect('blog:detail', pk=pk)

        # form.add_error('폼이 유효하지 않습니다.')
        hashtag_form = HashTagForm()
        context = {
            "title": "Blog",
            'post': post,
            'comments': post.comment_set.all(),
            'hashtags': post.hashtag_set.all(),
            'comment_form': form,
            'hashtag_form': hashtag_form
        }
        return render(request, 'blog/post_detail.html', context)


class CommentDelete(View):
    def post(self, reqeust, pk):
        # 커멘트 객체 가져오기
        comment = Comment.objects.get(pk=pk)

        post_id = comment.post.id
        # 댓글 삭제 로직 구현
        comment.delete()

        return redirect('blog:detail', pk=post_id)


class HashTagWrite(View):

    def post(self, request, pk):
        form = HashTagForm(request.POST)
        post = Post.objects.get(pk=pk)
        if form.is_valid():
            name = form.cleaned_data['name']
            writer = request.user
            hashtag = HashTag.objects.create(
                post=post, name=name, writer=writer)
            return redirect('blog:detail', post_id=pk)
        form.add_error(None, '폼이 유효하지 않습니다.')
        comment_form = CommentForm()
        context = {
            'title': 'Blog',
            'post': post,
            'comments': post.comment_set.all(),
            'hashtags': post.hashtag_set.all(),
            'comment_form': comment_form,
            'hashtag_form': form
        }
        return render(request, 'blog/post_detail.html', context)


class HashTagDelete(View):
    def post(self, reqeust, pk):
        # 커멘트 객체 가져오기
        hasgtag = HashTag.objects.get(pk=pk)

        post_id = hasgtag.post.id
        # 댓글 삭제 로직 구현
        hasgtag.delete()

        return redirect('blog:detail', pk=post_id)

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="ko">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>블로그</title>
  </head>

  <body>
    <div class="container">
      <h1>블로그</h1>
      <hr>
      {% block content %}{% endblock %}
    </div>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>

</html>

blog/templates/blog/form_error.html
<!-- form error 출력 -->

<div class="alert alert-danger">
  {{ form }}
  </div>

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block content %}

  <!-- 내용 추가 -->
  <!-- form error -->
  <h2>제목:
    {{ post.title }}</h2>

  {% if post.writer == request.user %}
    <a href="{% url 'blog:edit' pk=post.pk %}" class="btn">수정</a>
    <form action="{% url 'blog:delete' pk=post.pk %}" method="post">
      {% csrf_token %}
      <input type="submit" value="삭제" class="btn">
    </form>
  {% endif %}

  <p>내용:
    {{ post.content }}</p>
  <p>작성자:
    {{ post.writer }}</p>
  <p>작성일:
    {{ post.created_at }}</p>
  <hr>

  <!-- 작성 화면 -->
  <h3>댓글</h3>
  <form action="{% url 'blog:cm-write' pk=post.pk %}" method="post">
    {% csrf_token %}
    {% if comment_form.errors %}
      {% with form = comment_form %}
      {% include 'blog/form_error.html' %}
      {% endwith %}
    {% else %}
      {{ comment_form.content }}
    {% endif %}
    <input type="submit" value="댓글 작성">
  </form>
  <br>
  <!-- comments -->
  <!-- if 문 -->
  {% if comments %}
    <!-- for 문 -->
    <ul>
      {% for comment in comments %}
        <!-- 내용, 작성시간, 삭제 버튼 -->
        <li>{{ comment.content }}
          /
          {{ comment.created_at }}
          {% if comment.writer == request.user %}
            <form action="{% url 'blog:cm-delete' pk=comment.pk %}" method="post">
              {% csrf_token %}
              <input type="submit" value="X" class='btn'>
            </form>
          {% endif %}
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>댓글이 없습니다.</p>
  {% endif %}
  <hr>
  <!-- 태그작성 화면 -->
  <h3>해시태그</h3>
  <form action="{% url 'blog:tag-write' pk=post.pk %}" method="post">
    {% csrf_token %}
    {% if hashtag_form.errors %}
      {% with form = hashtag_form %}
      {% include 'blog/form_error.html' %}
      {% endwith %}
    {% else %}
      {{ hashtag_form.name }}
    {% endif %}
    <input type="submit" value="태그 작성">
  </form>
  {% if hashtags %}
    <ul>
      {% for hashtag in hashtags %}
        <li>
          {{ hashtag }}
          {% if hashtag.writer == request.user %}
            <form action="{% url 'blog:tag-delete' pk=hashtag.pk %}" method="post">
              {% csrf_token %}
              <input type="submit" value="X" class='btn'>
            </form>
          {% endif %}
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <br>
    <p>해시태그가 없습니다.</p>
  {% endif %}
{% endif %}
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'base.html' %}

{% block content %}

  {% if form %}
    {% include 'blog/form_error.html' %}
  {% else %}
    <form action="{% url 'blog:edit' pk=post.pk %}" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="수정">
    </form>
  {% endif %}
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'base.html' %}

{% block content %}
  <h2>블로그 글 작성 화면<h1>
      <!-- 제목 -->
      <!-- 내용 -->
      <form action="{% url 'blog:write' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
      </form>
    {% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>블로그 게시판 화면</h1>
  <p>블로그 게시판 첫 화면입니다.</p>
  <form action="{% url 'blog:write' %}" method="get">
    <input type="hidden" name="{{ redirect_field_name }}" value="{{ request.GET.next }}">
    <input type="submit" value="글 작성">
  </form>
  {# <a href="{% url 'blog:write' %}" class="btn btn-outline-success">글 작성</a> #}
  <!-- 글이 있을 때 -->
  {% if posts %}
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>제목</th>
          <th>본문</th>
          <th>작성자</th>
        </tr>
      </thead>
      <tbody>
        {% for post in posts %}
          <tr>
            <td>
              <a href="{% url 'blog:detail' pk=post.pk %}">{{ post.title }}</a>
            </td>
            <td>{{ post.content }}</td>
            <td>{{ post.writer }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <!-- 글이 없을 때 -->
    <p>글이 없습니다.</p>
  {% endif %}
{% endblock %}