app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
    path('', views.IndexMain.as_view())
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    # user/
    # 회원가입
    path('register/', views.Registration.as_view(), name='register'),
    # 로그인
    path('login/', views.Login.as_view(), name='login'),
    # 로그아웃
    path('logout/', views.Logout.as_view(), name='logout'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>
      {% block title %}
        {{ title }}
      {% endblock %}
    </title>
  </head>

  <body>
    <div class="container">
      {% if user.is_authenticated %}
        <p>Welcome,
          {{ user.email }}</p>
        <a href="{% url 'user:logout' %}" class="btn">Logout</a>
      {% else %}
        <p>Please, Login</p>
        <a href="{% url 'user:login' %}" class="btn">Login</a>
      {% endif %}
      <h1>블로그</h1>
      <hr>
      {% block content %}{% endblock %}
    </div>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>

</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
  <h1>Index page</h1>
  <a href="{% url 'user:register' %}" class="btn">회원가입</a>
  <a href="{% url 'user:login' %}" class="btn">로그인</a>
{% endblock %}